# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Nodejs version
        uses: actions/setup-node@v1
        with:
          node-version: '10.17'
      - name: Install npm dependencies
        run:   npm install 
      - name: Install dependencies to build Windows bundle
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt-get install software-properties-common
          sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ xenial main'
          sudo apt-get update
          sudo apt-get install -y --install-recommends wine nsis
      - name: Build Linux & Microsoft Windows package
        run:  npm run build
  
