name: 'Test artifacts'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Test creating dist files
        run:  dd if=/dev/random of=test-generated.dat  bs=32M  count=1
      - name: 'Upload artifact'
        uses: actions/upload-artifact@master
        with:
          path: test-generated.dat
